language: haskell
install:
  - git clone git://github.com/elm-lang/Elm
  - git clone git://github.com/maxsnew/IO
  - cd IO
  - cabal sandbox init
  - cabal sandbox add-source ../Elm
  - cabal install
  - sudo cp .cabal-sandbox/bin/elm    /usr/local/bin/elm
  - sudo cp .cabal-sandbox/bin/elm-io /usr/local/bin/elm-io
  - cd ..
  - npm install jsdom
before_script: elm-io --default-ports Tests/Tests.elm tests.js
script: node tests.js
